"""Add markdown_id field to issues table

Revision ID: 45ab04d6adfc
Revises: ed1d26e0873a
Create Date: 2025-10-16 00:45:29.491996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ab04d6adfc'
down_revision: Union[str, Sequence[str], None] = 'ed1d26e0873a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('markdown_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'markdown_id')
    # ### end Alembic commands ###
