"""Initial schema

Revision ID: 4bfcc158532b
Revises: 
Create Date: 2025-10-15 12:35:33.881398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfcc158532b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('design', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'CLOSED', name='status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('BUG', 'FEATURE', 'TASK', 'EPIC', 'CHORE', name='issuetype'), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('issue_id', sa.String(length=50), nullable=False),
    sa.Column('depends_on_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('BLOCKS', 'RELATED', 'PARENT_CHILD', name='dependencytype'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'depends_on_id'),
    sa.UniqueConstraint('issue_id', 'depends_on_id', name='unique_dependency')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'UPDATED', 'STATUS_CHANGED', 'COMMENTED', 'CLOSED', 'REOPENED', 'DEPENDENCY_ADDED', 'DEPENDENCY_REMOVED', 'LABEL_ADDED', 'LABEL_REMOVED', name='eventtype'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('issue_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'label'),
    sa.UniqueConstraint('issue_id', 'label', name='unique_issue_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels')
    op.drop_table('events')
    op.drop_table('dependencies')
    op.drop_table('issues')
    # ### end Alembic commands ###
